# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_auto_20160316_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'JobDB',
            },
        ),
        migrations.AlterField(
            model_name='priority',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
