# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0004_auto_20160421_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdb',
            name='priority',
            field=models.CharField(max_length=4),
        ),
    ]
